CREATE SCHEMA IF NOT EXISTS hospital_management_db;
SET search_path TO hospital_management_db;

CREATE TABLE IF NOT EXISTS Department (
    department_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    location VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Medical_Staff (
    staff_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    full_name VARCHAR(101) GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED,
    role VARCHAR(50) NOT NULL,
    phone VARCHAR(20) UNIQUE,
    email VARCHAR(100) UNIQUE,
    department_id INT REFERENCES Department(department_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Patient (
    patient_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    full_name VARCHAR(101) GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED,
    date_of_birth DATE NOT NULL CHECK (date_of_birth < CURRENT_DATE),
    gender VARCHAR(10) CHECK (gender IN ('Male', 'Female', 'Other')),
    phone VARCHAR(20),
    address VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Room (
    room_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(10) UNIQUE NOT NULL,
    capacity INT CHECK (capacity > 0),
    department_id INT REFERENCES Department(department_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Appointment (
    appointment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_date TIMESTAMP NOT NULL CHECK (appointment_date > '2026-01-01'),
    status VARCHAR(20) NOT NULL CHECK (status IN ('Scheduled', 'Completed', 'Cancelled')),
    patient_id INT REFERENCES Patient(patient_id) ON DELETE CASCADE,
    staff_id INT REFERENCES Medical_Staff(staff_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Medical_Record (
    record_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diagnosis TEXT,
    record_date DATE CHECK (record_date > '2026-01-01'),
    patient_id INT REFERENCES Patient(patient_id) ON DELETE CASCADE,
    staff_id INT REFERENCES Medical_Staff(staff_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS Treatment (
    treatment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    cost DECIMAL(10, 2) CHECK (cost >= 0)
);

CREATE TABLE IF NOT EXISTS Patient_Treatment (
    patient_id INT REFERENCES Patient(patient_id) ON DELETE CASCADE,
    treatment_id INT REFERENCES Treatment(treatment_id) ON DELETE CASCADE,
    start_date DATE CHECK (start_date > '2026-01-01'),
    end_date DATE,
    notes TEXT,
    PRIMARY KEY (patient_id, treatment_id)
);

CREATE TABLE IF NOT EXISTS Room_Assignment (
    assignment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_date DATE CHECK (admission_date > '2026-01-01'),
    discharge_date DATE,
    patient_id INT REFERENCES Patient(patient_id) ON DELETE CASCADE,
    room_id INT REFERENCES Room(room_id) ON DELETE CASCADE,
    CHECK (discharge_date >= admission_date)
);

CREATE TABLE IF NOT EXISTS Billing (
    bill_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_amount DECIMAL(10, 2) NOT NULL CHECK (total_amount >= 0),
    payment_status VARCHAR(20) CHECK (payment_status IN ('Paid', 'Pending', 'Cancelled')),
    bill_date TIMESTAMP CHECK (bill_date > '2026-01-01'),
    patient_id INT REFERENCES Patient(patient_id) ON DELETE CASCADE
    treatment_id INT REFERENCES Treatment(treatment_id) ON DELETE CASCADE
);

TRUNCATE TABLE 
    Billing,
    Room_Assignment,
    Patient_Treatment,
    Medical_Record,
    Appointment,
    Treatment,
    Room,
    Patient,
    Medical_Staff,
    Department 
RESTART IDENTITY CASCADE;

INSERT INTO Department (name, location) VALUES ('Cardiology', 'Floor 1');

INSERT INTO Medical_Staff (first_name, last_name, role, department_id) 
VALUES ('Michael', 'Adams', 'Doctor', 1);

INSERT INTO Patient (first_name, last_name, date_of_birth, gender) 
VALUES ('John', 'Smith', '1990-05-12', 'Male');

INSERT INTO Appointment (appointment_date, status, patient_id, staff_id) 
VALUES ('2026-05-10 10:00:00', 'Scheduled', 1, 1);
